# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170wAtl55KaF1JVL9y5z9OGStp9PnPgGF
"""

import numpy as np

A= [[1,0,0,9,0,0],[5,0,0,0,0,0],[0,-3,0,0,2,0],[0,0,5,0,0,-1],[0,0,0,2,0,0],[0,7,0,0,0,1]]
A=np.asarray(A)

Anz=[]
JA=[]
IA=np.zeros(A.shape[0]+1)
drow=True
nz=0
k=0
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    if np.all(A[i]==0) :
      k=k+1
      if i==A.shape[0]-1:
        IA[-1]=nz+1
        if drow:
          if IA[i-1]==0:
            for v in range(k):
              IA[i-v]=nz+1
              drow=False
          elif IA[i]==0:
            IA[i]=nz+1
      break
    elif A[i][j]==0:
      pass
    elif A[i][j]!=0:
      Anz.append(A[i][j])
      JA.append(j+1)
      nz=nz+1
      if drow:
        if i==0:
          IA[i]=nz
          drow=False

        elif IA[i-1]==0:
          for v in range(k+1):
            IA[i-v]=nz
            drow=False
            k=0
        
        else:
          IA[i]=nz
          drow=False
  IA[-1]=nz+1
  drow=True


print(Anz)
print(JA)
print(IA)